export const ABI = [
  {
    inputs: [
      { internalType: 'contract IERC20', name: 'tokenUSDT', type: 'address' },
      { internalType: 'contract IERC20', name: 'tokenBUSD', type: 'address' },
      { internalType: 'contract IERC20', name: 'tokenKS', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address', name: 'applyAddress', type: 'address' },
      { internalType: 'string', name: 'jobName', type: 'string' },
      { internalType: 'uint256', name: 'amountBefore', type: 'uint256' },
      { internalType: 'string', name: 'timeStar', type: 'string' },
      { internalType: 'uint256', name: 'estimate', type: 'uint256' },
      { internalType: 'uint256', name: 'typeJob', type: 'uint256' },
    ],
    name: 'CreateJobBNB',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'applyAddress', type: 'address' },
      { internalType: 'string', name: 'jobName', type: 'string' },
      { internalType: 'uint256', name: 'amountAfter', type: 'uint256' },
      { internalType: 'uint256', name: 'amountBefore', type: 'uint256' },
      { internalType: 'string', name: 'timeStar', type: 'string' },
      { internalType: 'uint256', name: 'estimate', type: 'uint256' },
      { internalType: 'uint256', name: 'typeJob', type: 'uint256' },
    ],
    name: 'CreateJobBUSD',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'applyAddress', type: 'address' },
      { internalType: 'string', name: 'jobName', type: 'string' },
      { internalType: 'uint256', name: 'amountAfter', type: 'uint256' },
      { internalType: 'uint256', name: 'amountBefore', type: 'uint256' },
      { internalType: 'string', name: 'timeStar', type: 'string' },
      { internalType: 'uint256', name: 'estimate', type: 'uint256' },
      { internalType: 'uint256', name: 'typeJob', type: 'uint256' },
    ],
    name: 'CreateJobKS',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'applyAddress', type: 'address' },
      { internalType: 'string', name: 'jobName', type: 'string' },
      { internalType: 'uint256', name: 'amountAfter', type: 'uint256' },
      { internalType: 'uint256', name: 'amountBefore', type: 'uint256' },
      { internalType: 'string', name: 'timeStar', type: 'string' },
      { internalType: 'uint256', name: 'estimate', type: 'uint256' },
      { internalType: 'uint256', name: 'typeJob', type: 'uint256' },
    ],
    name: 'CreateJobUSDT',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'FetchAllJobs',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'jobID', type: 'uint256' },
          { internalType: 'uint256', name: 'workerReceive', type: 'uint256' },
          { internalType: 'uint256', name: 'priceBeforeFee', type: 'uint256' },
          { internalType: 'uint256', name: 'priceAfterFee', type: 'uint256' },
          { internalType: 'uint256', name: 'typeJob', type: 'uint256' },
          { internalType: 'uint256', name: 'feeBuyer', type: 'uint256' },
          { internalType: 'uint256', name: 'feeSeller', type: 'uint256' },
          { internalType: 'uint256', name: 'estimate', type: 'uint256' },
          { internalType: 'uint256', name: 'createDate', type: 'uint256' },
          { internalType: 'uint256', name: 'complainWorker', type: 'uint256' },
          { internalType: 'uint256', name: 'complainOwner', type: 'uint256' },
          { internalType: 'uint256', name: 'typeToken', type: 'uint256' },
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'address', name: 'worker', type: 'address' },
          { internalType: 'string', name: 'jobName', type: 'string' },
          { internalType: 'string', name: 'timeStar', type: 'string' },
          { internalType: 'bool', name: 'ownerConfirm', type: 'bool' },
          { internalType: 'bool', name: 'ownerComplaint', type: 'bool' },
          { internalType: 'bool', name: 'adminConfirm', type: 'bool' },
          { internalType: 'bool', name: 'status', type: 'bool' },
        ],
        internalType: 'struct KSService.ListJobInfo[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'FetchCompleteJobs',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'jobID', type: 'uint256' },
          { internalType: 'uint256', name: 'workerReceive', type: 'uint256' },
          { internalType: 'uint256', name: 'priceBeforeFee', type: 'uint256' },
          { internalType: 'uint256', name: 'priceAfterFee', type: 'uint256' },
          { internalType: 'uint256', name: 'typeJob', type: 'uint256' },
          { internalType: 'uint256', name: 'feeBuyer', type: 'uint256' },
          { internalType: 'uint256', name: 'feeSeller', type: 'uint256' },
          { internalType: 'uint256', name: 'estimate', type: 'uint256' },
          { internalType: 'uint256', name: 'createDate', type: 'uint256' },
          { internalType: 'uint256', name: 'complainWorker', type: 'uint256' },
          { internalType: 'uint256', name: 'complainOwner', type: 'uint256' },
          { internalType: 'uint256', name: 'typeToken', type: 'uint256' },
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'address', name: 'worker', type: 'address' },
          { internalType: 'string', name: 'jobName', type: 'string' },
          { internalType: 'string', name: 'timeStar', type: 'string' },
          { internalType: 'bool', name: 'ownerConfirm', type: 'bool' },
          { internalType: 'bool', name: 'ownerComplaint', type: 'bool' },
          { internalType: 'bool', name: 'adminConfirm', type: 'bool' },
          { internalType: 'bool', name: 'status', type: 'bool' },
        ],
        internalType: 'struct KSService.ListJobInfo[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'FetchOwnerJobs',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'jobID', type: 'uint256' },
          { internalType: 'uint256', name: 'workerReceive', type: 'uint256' },
          { internalType: 'uint256', name: 'priceBeforeFee', type: 'uint256' },
          { internalType: 'uint256', name: 'priceAfterFee', type: 'uint256' },
          { internalType: 'uint256', name: 'typeJob', type: 'uint256' },
          { internalType: 'uint256', name: 'feeBuyer', type: 'uint256' },
          { internalType: 'uint256', name: 'feeSeller', type: 'uint256' },
          { internalType: 'uint256', name: 'estimate', type: 'uint256' },
          { internalType: 'uint256', name: 'createDate', type: 'uint256' },
          { internalType: 'uint256', name: 'complainWorker', type: 'uint256' },
          { internalType: 'uint256', name: 'complainOwner', type: 'uint256' },
          { internalType: 'uint256', name: 'typeToken', type: 'uint256' },
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'address', name: 'worker', type: 'address' },
          { internalType: 'string', name: 'jobName', type: 'string' },
          { internalType: 'string', name: 'timeStar', type: 'string' },
          { internalType: 'bool', name: 'ownerConfirm', type: 'bool' },
          { internalType: 'bool', name: 'ownerComplaint', type: 'bool' },
          { internalType: 'bool', name: 'adminConfirm', type: 'bool' },
          { internalType: 'bool', name: 'status', type: 'bool' },
        ],
        internalType: 'struct KSService.ListJobInfo[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'FetchWorkerJobs',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'jobID', type: 'uint256' },
          { internalType: 'uint256', name: 'workerReceive', type: 'uint256' },
          { internalType: 'uint256', name: 'priceBeforeFee', type: 'uint256' },
          { internalType: 'uint256', name: 'priceAfterFee', type: 'uint256' },
          { internalType: 'uint256', name: 'typeJob', type: 'uint256' },
          { internalType: 'uint256', name: 'feeBuyer', type: 'uint256' },
          { internalType: 'uint256', name: 'feeSeller', type: 'uint256' },
          { internalType: 'uint256', name: 'estimate', type: 'uint256' },
          { internalType: 'uint256', name: 'createDate', type: 'uint256' },
          { internalType: 'uint256', name: 'complainWorker', type: 'uint256' },
          { internalType: 'uint256', name: 'complainOwner', type: 'uint256' },
          { internalType: 'uint256', name: 'typeToken', type: 'uint256' },
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'address', name: 'worker', type: 'address' },
          { internalType: 'string', name: 'jobName', type: 'string' },
          { internalType: 'string', name: 'timeStar', type: 'string' },
          { internalType: 'bool', name: 'ownerConfirm', type: 'bool' },
          { internalType: 'bool', name: 'ownerComplaint', type: 'bool' },
          { internalType: 'bool', name: 'adminConfirm', type: 'bool' },
          { internalType: 'bool', name: 'status', type: 'bool' },
        ],
        internalType: 'struct KSService.ListJobInfo[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ListConfigKS',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'configID', type: 'uint256' },
          { internalType: 'uint256', name: 'rate', type: 'uint256' },
          { internalType: 'uint256', name: 'feeSystem', type: 'uint256' },
          { internalType: 'address', name: 'addressToken', type: 'address' },
          { internalType: 'uint256', name: 'typeToken', type: 'uint256' },
        ],
        internalType: 'struct KSService.ConfigKS[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'bool', name: 'ownerComplaint', type: 'bool' },
    ],
    name: 'OwnerConfirmJob',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'uint256', name: 'percentOwner', type: 'uint256' },
      { internalType: 'uint256', name: 'feeManage', type: 'uint256' },
    ],
    name: 'adminConfirmJob',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'rate', type: 'uint256' },
      { internalType: 'uint256', name: 'feeSystem', type: 'uint256' },
      { internalType: 'address', name: 'addressToken', type: 'address' },
      { internalType: 'uint256', name: 'typeToken', type: 'uint256' },
    ],
    name: 'createConfigKS',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'uint256', name: 'rate', type: 'uint256' },
      { internalType: 'uint256', name: 'feeSystem', type: 'uint256' },
      { internalType: 'address', name: 'addressToken', type: 'address' },
      { internalType: 'uint256', name: 'typeToken', type: 'uint256' },
    ],
    name: 'editConfigKS',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'typeToken', type: 'uint256' }],
    name: 'getBalance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'withdrawAll',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    name: 'withdrawByJob',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'withdrawOwner',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]

export const USDT_ABI = [
  {
    inputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'spender',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'value',
        type: 'uint256',
      },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      { indexed: true, internalType: 'address', name: 'to', type: 'address' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'value',
        type: 'uint256',
      },
    ],
    name: 'Transfer',
    type: 'event',
  },
  {
    constant: true,
    inputs: [],
    name: '_decimals',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: '_name',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: '_symbol',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'address', name: 'spender', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { internalType: 'address', name: 'spender', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'burn',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'decimals',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { internalType: 'address', name: 'spender', type: 'address' },
      { internalType: 'uint256', name: 'subtractedValue', type: 'uint256' },
    ],
    name: 'decreaseAllowance',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'getOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { internalType: 'address', name: 'spender', type: 'address' },
      { internalType: 'uint256', name: 'addedValue', type: 'uint256' },
    ],
    name: 'increaseAllowance',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: false,
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'mint',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'name',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'symbol',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'totalSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { internalType: 'address', name: 'recipient', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { internalType: 'address', name: 'sender', type: 'address' },
      { internalType: 'address', name: 'recipient', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
]
